name: CI/CD Pipeline App Tarefas

on:
  push:
    branches: [ "main", "joaoPedro" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4
      
      - name: Instalar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Instalar Dependências da Raiz
        run: npm install
        
      - name: Instalar Dependências do Frontend
        run: |
          cd frontend
          npm install

      # --- PASSO NOVO: TESTES DO BACKEND (JEST) ---
      - name: Rodar Testes do Backend
        run: npm test -- --json --outputFile=test-report-backend.json
        
      # --- PASSO NOVO: TESTES DO FRONTEND (ANGULAR) ---
      - name: Rodar Testes do Frontend
        run: |
          cd frontend
          npx ng test --watch=false --browsers=ChromeHeadless
        
      - name: Salvar Relatórios como Artefato
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: relatorios-de-testes
          path: |
            test-report-backend.json
            frontend/test-report.json

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4
        
      - name: Empacotar o Projeto (Build)
        run: zip -r pacote-deploy.zip backend/ frontend/ package.json
        
      - name: Salvar Pacote (Build) como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: pacote-aplicacao
          path: pacote-deploy.zip

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Acionar Deploy no Render
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
            echo "A URL do Render ainda não foi configurada. Pulando."
          else
            curl "${{ secrets.RENDER_DEPLOY_HOOK }}"
          fi

  notify:
    needs: [test, build, deploy]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4
        
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Executar Script de Notificação
        env:
          EMAIL_DESTINO: ${{ secrets.EMAIL }}
          STATUS_PIPELINE: ${{ needs.test.result }} # Puxa o status real dos testes
        run: node script-notificacao.js